const TRADE_SOURCES = [

  // ── SPORT-SPECIFIC TRADE MEDIA ─────────────────────────────────────────────
  { id: "footballscoop",      name: "FootballScoop",               url: "https://footballscoop.com/feed/",                           sport: "football",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "on3",                name: "On3 Sports",                  url: "https://www.on3.com/feed/",                                 sport: "multiple",   divisions: ["DI"] },
  { id: "swimswam",           name: "SwimSwam",                    url: "https://swimswam.com/feed/",                                sport: "swimming",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "d1baseball",         name: "D1Baseball",                  url: "https://d1baseball.com/feed/",                              sport: "baseball",   divisions: ["DI"] },
  { id: "d1softball",         name: "D1Softball",                  url: "https://d1softball.com/feed/",                              sport: "softball",   divisions: ["DI"] },
  { id: "nfca",               name: "NFCA",                        url: "https://nfca.org/feed",                                     sport: "softball",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "laxallstars",        name: "Lax All Stars",               url: "https://laxallstars.com/feed",                              sport: "lacrosse",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "collegehockeynews",  name: "College Hockey News",         url: "https://www.collegehockeynews.com/rss/",                    sport: "hockey",     divisions: ["DI","DII","DIII"] },
  { id: "topdrawersoccer",    name: "TopDrawer Soccer",            url: "https://www.topdrawersoccer.com/rss",                       sport: "soccer",     divisions: ["DI","DII","DIII","NAIA"] },
  { id: "intermatwrestle",    name: "InterMat Wrestling",          url: "https://intermatwrestle.com/articles/rss",                  sport: "wrestling",  divisions: ["DI","DII","DIII","NAIA"] },
  { id: "row2k",              name: "Row2k",                       url: "https://www.row2k.com/rss/news.xml",                        sport: "rowing",     divisions: ["DI","DII","DIII"] },
  { id: "ustfccca",           name: "USTFCCCA",                    url: "https://www.ustfccca.org/feed",                             sport: "track",      divisions: ["DI","DII","DIII","NAIA"] },
  { id: "volleyballmag",      name: "Volleyball Magazine",         url: "https://volleyballmag.com/feed/",                           sport: "volleyball", divisions: ["DI","DII","DIII","NAIA"] },
  { id: "ncaa_news",          name: "NCAA News",                   url: "https://www.ncaa.org/rss/news",                             sport: "multiple",   divisions: ["DI","DII","DIII"] },
  { id: "d2football",         name: "D2Football.com",              url: "https://www.d2football.com/feed/",                          sport: "football",   divisions: ["DII"] },
  { id: "d2football_news",    name: "D2Football News",             url: "https://www.d2football.com/front-page-news/feed/",          sport: "football",   divisions: ["DII"] },

  // ── ESPN ───────────────────────────────────────────────────────────────────
  { id: "espn_top",           name: "ESPN",                        url: "https://www.espn.com/espn/rss/news",                        sport: "multiple",   divisions: ["DI"] },
  { id: "espn_ncaaf",         name: "ESPN College Football",       url: "https://www.espn.com/espn/rss/ncf/news",                    sport: "football",   divisions: ["DI"] },
  { id: "espn_ncaab",         name: "ESPN College Basketball",     url: "https://www.espn.com/espn/rss/ncb/news",                    sport: "basketball", divisions: ["DI"] },
  { id: "espn_ncaaw",         name: "ESPN Women's Basketball",     url: "https://www.espn.com/espn/rss/ncw/news",                    sport: "basketball", divisions: ["DI"] },
  { id: "espn_college",       name: "ESPN College Sports",         url: "https://www.espn.com/espn/rss/college-sports/news",         sport: "multiple",   divisions: ["DI"] },

  // ── YAHOO SPORTS ──────────────────────────────────────────────────────────
  { id: "yahoo_ncaaf",        name: "Yahoo College Football",      url: "https://sports.yahoo.com/college-football/rss/",            sport: "football",   divisions: ["DI"] },
  { id: "yahoo_ncaab",        name: "Yahoo College Basketball",    url: "https://sports.yahoo.com/college-basketball/rss/",          sport: "basketball", divisions: ["DI"] },
  { id: "yahoo_ncaaw",        name: "Yahoo Women's Basketball",    url: "https://sports.yahoo.com/womens-college-basketball/rss/",   sport: "basketball", divisions: ["DI"] },
  { id: "yahoo_ncaab2",       name: "Yahoo College Baseball",      url: "https://sports.yahoo.com/college-baseball/rss/",            sport: "baseball",   divisions: ["DI"] },
  { id: "yahoo_sports",       name: "Yahoo Sports",                url: "https://sports.yahoo.com/rss/",                             sport: "multiple",   divisions: ["DI"] },

  // ── NCAA SPORT-BY-SPORT FEEDS ─────────────────────────────────────────────
  { id: "ncaa_fb_fbs",        name: "NCAA Football FBS",           url: "https://www.ncaa.com/news/football/fbs/rss.xml",            sport: "football",   divisions: ["DI"] },
  { id: "ncaa_fb_fcs",        name: "NCAA Football FCS",           url: "https://www.ncaa.com/news/football/fcs/rss.xml",            sport: "football",   divisions: ["DI"] },
  { id: "ncaa_fb_d2",         name: "NCAA Football DII",           url: "https://www.ncaa.com/news/football/d2/rss.xml",             sport: "football",   divisions: ["DII"] },
  { id: "ncaa_fb_d3",         name: "NCAA Football DIII",          url: "https://www.ncaa.com/news/football/d3/rss.xml",             sport: "football",   divisions: ["DIII"] },
  { id: "ncaa_mbb_d1",        name: "NCAA Men's Basketball DI",    url: "https://www.ncaa.com/news/basketball-men/d1/rss.xml",       sport: "basketball", divisions: ["DI"] },
  { id: "ncaa_mbb_d2",        name: "NCAA Men's Basketball DII",   url: "https://www.ncaa.com/news/basketball-men/d2/rss.xml",       sport: "basketball", divisions: ["DII"] },
  { id: "ncaa_mbb_d3",        name: "NCAA Men's Basketball DIII",  url: "https://www.ncaa.com/news/basketball-men/d3/rss.xml",       sport: "basketball", divisions: ["DIII"] },
  { id: "ncaa_wbb_d1",        name: "NCAA Women's Basketball DI",  url: "https://www.ncaa.com/news/basketball-women/d1/rss.xml",     sport: "basketball", divisions: ["DI"] },
  { id: "ncaa_wbb_d2",        name: "NCAA Women's Basketball DII", url: "https://www.ncaa.com/news/basketball-women/d2/rss.xml",     sport: "basketball", divisions: ["DII"] },
  { id: "ncaa_wbb_d3",        name: "NCAA Women's Basketball DIII",url: "https://www.ncaa.com/news/basketball-women/d3/rss.xml",     sport: "basketball", divisions: ["DIII"] },
  { id: "ncaa_bsb_d1",        name: "NCAA Baseball DI",            url: "https://www.ncaa.com/news/baseball/d1/rss.xml",             sport: "baseball",   divisions: ["DI"] },
  { id: "ncaa_bsb_d2",        name: "NCAA Baseball DII",           url: "https://www.ncaa.com/news/baseball/d2/rss.xml",             sport: "baseball",   divisions: ["DII"] },
  { id: "ncaa_bsb_d3",        name: "NCAA Baseball DIII",          url: "https://www.ncaa.com/news/baseball/d3/rss.xml",             sport: "baseball",   divisions: ["DIII"] },
  { id: "ncaa_sft_d1",        name: "NCAA Softball DI",            url: "https://www.ncaa.com/news/softball/d1/rss.xml",             sport: "softball",   divisions: ["DI"] },
  { id: "ncaa_sft_d2",        name: "NCAA Softball DII",           url: "https://www.ncaa.com/news/softball/d2/rss.xml",             sport: "softball",   divisions: ["DII"] },
  { id: "ncaa_sft_d3",        name: "NCAA Softball DIII",          url: "https://www.ncaa.com/news/softball/d3/rss.xml",             sport: "softball",   divisions: ["DIII"] },
  { id: "ncaa_soc_m",         name: "NCAA Men's Soccer DI",        url: "https://www.ncaa.com/news/soccer-men/d1/rss.xml",           sport: "soccer",     divisions: ["DI"] },
  { id: "ncaa_soc_w",         name: "NCAA Women's Soccer DI",      url: "https://www.ncaa.com/news/soccer-women/d1/rss.xml",         sport: "soccer",     divisions: ["DI"] },
  { id: "ncaa_swm_m",         name: "NCAA Men's Swimming DI",      url: "https://www.ncaa.com/news/swimming-men/d1/rss.xml",         sport: "swimming",   divisions: ["DI"] },
  { id: "ncaa_swm_w",         name: "NCAA Women's Swimming DI",    url: "https://www.ncaa.com/news/swimming-women/d1/rss.xml",       sport: "swimming",   divisions: ["DI"] },
  { id: "ncaa_trk_m",         name: "NCAA Men's Track DI",         url: "https://www.ncaa.com/news/trackfield-outdoor-men/d1/rss.xml",   sport: "track",  divisions: ["DI"] },
  { id: "ncaa_trk_w",         name: "NCAA Women's Track DI",       url: "https://www.ncaa.com/news/trackfield-outdoor-women/d1/rss.xml", sport: "track",  divisions: ["DI"] },
  { id: "ncaa_vb_d1",         name: "NCAA Volleyball DI",          url: "https://www.ncaa.com/news/volleyball-women/d1/rss.xml",     sport: "volleyball", divisions: ["DI"] },
  { id: "ncaa_lax_m",         name: "NCAA Men's Lacrosse DI",      url: "https://www.ncaa.com/news/lacrosse-men/d1/rss.xml",         sport: "lacrosse",   divisions: ["DI"] },
  { id: "ncaa_lax_w",         name: "NCAA Women's Lacrosse DI",    url: "https://www.ncaa.com/news/lacrosse-women/d1/rss.xml",       sport: "lacrosse",   divisions: ["DI"] },
  { id: "ncaa_hky_m",         name: "NCAA Men's Hockey DI",        url: "https://www.ncaa.com/news/icehockey-men/d1/rss.xml",        sport: "hockey",     divisions: ["DI"] },
  { id: "ncaa_wres",          name: "NCAA Wrestling DI",           url: "https://www.ncaa.com/news/wrestling-men/d1/rss.xml",        sport: "wrestling",  divisions: ["DI"] },
  { id: "ncaa_row",           name: "NCAA Rowing DI",              url: "https://www.ncaa.com/news/rowing/d1/rss.xml",               sport: "rowing",     divisions: ["DI"] },
  { id: "ncaa_gym_w",         name: "NCAA Women's Gymnastics DI",  url: "https://www.ncaa.com/news/gymnastics-women/d1/rss.xml",     sport: "gymnastics", divisions: ["DI"] },
  { id: "ncaa_ten_m",         name: "NCAA Men's Tennis DI",        url: "https://www.ncaa.com/news/tennis-men/d1/rss.xml",           sport: "tennis",     divisions: ["DI"] },
  { id: "ncaa_ten_w",         name: "NCAA Women's Tennis DI",      url: "https://www.ncaa.com/news/tennis-women/d1/rss.xml",         sport: "tennis",     divisions: ["DI"] },

  // ── DI CONFERENCES — POWER FOUR ───────────────────────────────────────────
  { id: "conf_acc",           name: "ACC",                         url: "https://theacc.com/rss.aspx",                              sport: "multiple",   divisions: ["DI"] },
  { id: "conf_big10",         name: "Big Ten",                     url: "https://bigten.org/rss.aspx",                              sport: "multiple",   divisions: ["DI"] },
  { id: "conf_big12",         name: "Big 12",                      url: "https://big12sports.com/rss.aspx",                         sport: "multiple",   divisions: ["DI"] },
  { id: "conf_sec",           name: "SEC",                         url: "https://secsports.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },

  // ── DI CONFERENCES — GROUP OF FIVE ────────────────────────────────────────
  { id: "conf_american",      name: "American Athletic",           url: "https://theamerican.org/rss.aspx",                         sport: "multiple",   divisions: ["DI"] },
  { id: "conf_cusa",          name: "Conference USA",              url: "https://conferenceusa.com/rss.aspx",                       sport: "multiple",   divisions: ["DI"] },
  { id: "conf_mac",           name: "MAC",                         url: "https://getsomemaction.com/rss.aspx",                      sport: "multiple",   divisions: ["DI"] },
  { id: "conf_mw",            name: "Mountain West",               url: "https://themw.com/rss.aspx",                               sport: "multiple",   divisions: ["DI"] },
  { id: "conf_sunbelt",       name: "Sun Belt",                    url: "https://sunbeltsports.org/rss.aspx",                       sport: "multiple",   divisions: ["DI"] },

  // ── DI CONFERENCES — FCS / MID-MAJOR ──────────────────────────────────────
  { id: "conf_bigsky",        name: "Big Sky",                     url: "https://bigskyconf.com/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_bigsouth",      name: "Big South",                   url: "https://bigsouthsports.com/rss.aspx",                      sport: "multiple",   divisions: ["DI"] },
  { id: "conf_caa",           name: "CAA",                         url: "https://caasports.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },
  { id: "conf_ivy",           name: "Ivy League",                  url: "https://ivyleague.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },
  { id: "conf_meac",          name: "MEAC",                        url: "https://meacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_mvc",           name: "Missouri Valley",             url: "https://mvc-sports.com/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_nec",           name: "Northeast Conference",        url: "https://northeastconference.org/rss.aspx",                 sport: "multiple",   divisions: ["DI"] },
  { id: "conf_ovc",           name: "Ohio Valley",                 url: "https://ovcsports.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },
  { id: "conf_patriot",       name: "Patriot League",              url: "https://patriotleague.org/rss.aspx",                       sport: "multiple",   divisions: ["DI"] },
  { id: "conf_socon",         name: "Southern Conference",         url: "https://soconsports.com/rss.aspx",                         sport: "multiple",   divisions: ["DI"] },
  { id: "conf_southland",     name: "Southland",                   url: "https://southland.org/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },
  { id: "conf_swac",          name: "SWAC",                        url: "https://swac.org/rss.aspx",                                sport: "multiple",   divisions: ["DI"] },

  // ── DI CONFERENCES — NON-FOOTBALL ─────────────────────────────────────────
  { id: "conf_americaeast",   name: "America East",                url: "https://americaeast.com/rss.aspx",                         sport: "multiple",   divisions: ["DI"] },
  { id: "conf_asun",          name: "ASUN",                        url: "https://asunsports.org/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_atlantic10",    name: "Atlantic 10",                 url: "https://atlantic10.com/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_bigeast",       name: "Big East",                    url: "https://bigeast.com/rss.aspx",                             sport: "multiple",   divisions: ["DI"] },
  { id: "conf_bigwest",       name: "Big West",                    url: "https://bigwest.org/rss.aspx",                             sport: "multiple",   divisions: ["DI"] },
  { id: "conf_horizon",       name: "Horizon League",              url: "https://horizonleague.org/rss.aspx",                       sport: "multiple",   divisions: ["DI"] },
  { id: "conf_maac",          name: "MAAC",                        url: "https://maacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DI"] },
  { id: "conf_summit",        name: "Summit League",               url: "https://thesummitleague.org/rss.aspx",                     sport: "multiple",   divisions: ["DI"] },
  { id: "conf_wcc",           name: "West Coast Conference",       url: "https://wccsports.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },
  { id: "conf_wac",           name: "WAC",                         url: "https://wacsports.com/rss.aspx",                           sport: "multiple",   divisions: ["DI"] },

  // ── DII CONFERENCES ───────────────────────────────────────────────────────
  { id: "conf_ccaa",          name: "CCAA",                        url: "https://goccaa.org/rss.aspx",                              sport: "multiple",   divisions: ["DII"] },
  { id: "conf_cacc",          name: "CACC",                        url: "https://caccathletics.org/rss.aspx",                       sport: "multiple",   divisions: ["DII"] },
  { id: "conf_ciaa",          name: "CIAA",                        url: "https://theciaa.com/rss.aspx",                             sport: "multiple",   divisions: ["DII"] },
  { id: "conf_carolinas",     name: "Conference Carolinas",        url: "https://conferencecarolinas.com/rss.aspx",                 sport: "multiple",   divisions: ["DII"] },
  { id: "conf_ecc",           name: "East Coast Conference",       url: "https://eccsports.org/rss.aspx",                           sport: "multiple",   divisions: ["DII"] },
  { id: "conf_gliac",         name: "GLIAC",                       url: "https://gliac.org/rss.aspx",                               sport: "multiple",   divisions: ["DII"] },
  { id: "conf_glvc",          name: "GLVC",                        url: "https://glvcsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DII"] },
  { id: "conf_gmac",          name: "G-MAC",                       url: "https://greatmidwestsports.com/rss.aspx",                  sport: "multiple",   divisions: ["DII"] },
  { id: "conf_gac",           name: "Great American",              url: "https://greatamericanconference.com/rss.aspx",             sport: "multiple",   divisions: ["DII"] },
  { id: "conf_gnac",          name: "GNAC",                        url: "https://gnacsports.com/news/rss/",                         sport: "multiple",   divisions: ["DII"] },
  { id: "conf_lsc",           name: "Lone Star",                   url: "https://lonestarconference.org/rss.aspx",                  sport: "multiple",   divisions: ["DII"] },
  { id: "conf_miaa_d2",       name: "MIAA (DII)",                  url: "https://themiaa.com/rss.aspx",                             sport: "multiple",   divisions: ["DII"] },
  { id: "conf_nsic",          name: "NSIC",                        url: "https://northernsun.org/rss.aspx",                         sport: "multiple",   divisions: ["DII"] },
  { id: "conf_rmac",          name: "RMAC",                        url: "https://rmacsports.org/rss.aspx",                          sport: "multiple",   divisions: ["DII"] },
  { id: "conf_ne10",          name: "NE10",                        url: "https://northeast10.org/rss.aspx",                         sport: "multiple",   divisions: ["DII"] },
  { id: "conf_psac",          name: "PSAC",                        url: "https://psacsports.org/rss.aspx",                          sport: "multiple",   divisions: ["DII"] },
  { id: "conf_mec",           name: "Mountain East",               url: "https://mountaineast.org/rss.aspx",                        sport: "multiple",   divisions: ["DII"] },
  { id: "conf_gsc",           name: "Gulf South",                  url: "https://gscsports.org/rss.aspx",                           sport: "multiple",   divisions: ["DII"] },
  { id: "conf_sac_d2",        name: "South Atlantic",              url: "https://thesac.com/rss.aspx",                              sport: "multiple",   divisions: ["DII"] },
  { id: "conf_siac",          name: "SIAC",                        url: "https://thesiac.com/rss.aspx",                             sport: "multiple",   divisions: ["DII"] },
  { id: "conf_ssc",           name: "Sunshine State",              url: "https://sunshinestateconference.com/rss.aspx",             sport: "multiple",   divisions: ["DII"] },
  { id: "conf_peachbelt",     name: "Peach Belt",                  url: "https://peachbeltconference.org/rss.aspx",                 sport: "multiple",   divisions: ["DII"] },

  // ── DIII CONFERENCES — NEW ENGLAND ────────────────────────────────────────
  { id: "d3_arc",             name: "American Rivers",             url: "https://rollrivers.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_ccc",             name: "Commonwealth Coast",          url: "https://cccathletics.com/rss.aspx",                        sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_lec",             name: "Little East",                 url: "https://littleeast.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_mascac",          name: "MASCAC",                      url: "https://mascac.com/rss.aspx",                              sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_newmac",          name: "NEWMAC",                      url: "https://newmacsports.com/rss.aspx",                        sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_nescac",          name: "NESCAC",                      url: "https://nescac.com/rss.aspx",                              sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_nac",             name: "North Atlantic",              url: "https://nacathletics.com/rss.aspx",                        sport: "multiple",   divisions: ["DIII"] },

  // ── DIII CONFERENCES — MID-ATLANTIC ───────────────────────────────────────
  { id: "d3_atleast",         name: "Atlantic East",               url: "https://atlanticeast.com/rss.aspx",                        sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_centennial",      name: "Centennial",                  url: "https://centennial.org/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_cunyac",          name: "CUNYAC",                      url: "https://cunyathletics.com/rss.aspx",                       sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_empire8",         name: "Empire 8",                    url: "https://empire8.com/rss.aspx",                             sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_landmark",        name: "Landmark",                    url: "https://landmarkconference.org/rss.aspx",                  sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_libertyleague",   name: "Liberty League",              url: "https://libertyleagueathletics.com/rss.aspx",              sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_mac",             name: "MAC (DIII)",                  url: "https://gomacsports.com/rss.aspx",                         sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_njac",            name: "NJAC",                        url: "https://njacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_skyline",         name: "Skyline",                     url: "https://skylineconference.org/rss.aspx",                   sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_sunyac",          name: "SUNYAC",                      url: "https://sunyac.com/rss.aspx",                              sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_unitedeast",      name: "United East",                 url: "https://unitedeast.org/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },

  // ── DIII CONFERENCES — MIDWEST ────────────────────────────────────────────
  { id: "d3_cciw",            name: "CCIW",                        url: "https://cciw.org/rss.aspx",                                sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_hcac",            name: "Heartland Collegiate",        url: "https://heartlandconf.org/rss.aspx",                       sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_miaa",            name: "MIAA (DIII)",                 url: "https://miaa.org/rss.aspx",                                sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_mwc",             name: "Midwest Conference",          url: "https://midwestconference.org/rss.aspx",                   sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_ncac",            name: "North Coast Athletic",        url: "https://northcoast.org/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_nacc",            name: "NACC",                        url: "https://naccsports.org/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_oac",             name: "Ohio Athletic",               url: "https://oac.org/rss.aspx",                                 sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_umac",            name: "UMAC",                        url: "https://umacathletics.com/rss.aspx",                       sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_wiac",            name: "WIAC",                        url: "https://wiacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },

  // ── DIII CONFERENCES — SOUTH ──────────────────────────────────────────────
  { id: "d3_asc",             name: "American Southwest",          url: "https://ascsports.org/rss.aspx",                           sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_ccs",             name: "Collegiate Conf South",       url: "https://ccsathletics.org/rss.aspx",                        sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_odac",            name: "ODAC",                        url: "https://odaconline.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_saa",             name: "Southern Athletic",           url: "https://saa-sports.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_usasouth",        name: "USA South",                   url: "https://usasouth.net/rss.aspx",                            sport: "multiple",   divisions: ["DIII"] },

  // ── DIII CONFERENCES — WEST ───────────────────────────────────────────────
  { id: "d3_nwc",             name: "Northwest Conference",        url: "https://nwcsports.com/rss.aspx",                           sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_sciac",           name: "SCIAC",                       url: "https://sciac.org/rss.aspx",                               sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_scac",            name: "SCAC",                        url: "https://scacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["DIII"] },
  { id: "d3_sliac",           name: "SLIAC",                       url: "https://sliac.org/rss.aspx",                               sport: "multiple",   divisions: ["DIII"] },

  // ── NAIA CONFERENCES ──────────────────────────────────────────────────────
  { id: "naia_aac",           name: "Appalachian Athletic",        url: "https://www.aacsports.com/rss/index",                      sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_cascade",       name: "Cascade Collegiate",          url: "https://cascadeconference.org/rss.aspx",                   sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_ccac",          name: "CCAC",                        url: "https://ccacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_crossroads",    name: "Crossroads League",           url: "https://crossroadsleague.com/rss-feeds",                   sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_frontier",      name: "Frontier Conference",         url: "https://frontierconference.com/rss.aspx",                  sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_gpac",          name: "GPAC",                        url: "https://gpacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_haac",          name: "Heart of America",            url: "https://heartofamericaconference.com/rss.aspx",            sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_kcac",          name: "KCAC",                        url: "https://kcacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_nsaa",          name: "North Star Athletic",         url: "https://playnorthstar.com/rss.aspx",                       sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_midsouth",      name: "Mid-South Conference",        url: "https://mid-southconference.org/rss.aspx",                 sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_ssac",          name: "Southern States Athletic",    url: "https://ssacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_sun",           name: "Sun Conference",              url: "https://thesunconference.com/rss.aspx",                    sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_calpac",        name: "Cal Pac",                     url: "https://calpacathletics.com/rss.aspx",                     sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_gsac",          name: "GSAC",                        url: "https://gsacsports.org/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_rrac",          name: "Red River Athletic",          url: "https://rracsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_sooner",        name: "Sooner Athletic",             url: "https://soonerathletic.org/rss.aspx",                      sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_cac",           name: "Continental Athletic",        url: "https://cacathletics.com/rss.aspx",                        sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_whac",          name: "WHAC",                        url: "https://whacsports.com/rss.aspx",                          sport: "multiple",   divisions: ["NAIA"] },
  { id: "naia_rsc",           name: "River States",                url: "https://riverstatesconference.com/rss.aspx",               sport: "multiple",   divisions: ["NAIA"] },
];

module.exports = { TRADE_SOURCES };
