const TRADE_SOURCES = [
  { id: "footballscoop",     name: "FootballScoop",       url: "https://footballscoop.com/feed/",                  sport: "football",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "on3",               name: "On3 Sports",          url: "https://www.on3.com/feed/",                        sport: "multiple",   divisions: ["DI"] },
  { id: "swimswam",          name: "SwimSwam",            url: "https://swimswam.com/feed/",                       sport: "swimming",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "d1baseball",        name: "D1Baseball",          url: "https://d1baseball.com/feed/",                     sport: "baseball",   divisions: ["DI"] },
  { id: "d1softball",        name: "D1Softball",          url: "https://d1softball.com/feed/",                     sport: "softball",   divisions: ["DI"] },
  { id: "nfca",              name: "NFCA",                url: "https://nfca.org/feed",                            sport: "softball",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "laxallstars",       name: "Lax All Stars",       url: "https://laxallstars.com/feed",                     sport: "lacrosse",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "collegehockeynews", name: "College Hockey News", url: "https://www.collegehockeynews.com/rss/",           sport: "hockey",     divisions: ["DI","DII","DIII"] },
  { id: "topdrawersoccer",   name: "TopDrawer Soccer",    url: "https://www.topdrawersoccer.com/rss",              sport: "soccer",     divisions: ["DI","DII","DIII","NAIA"] },
  { id: "intermatwrestle",   name: "InterMat Wrestling",  url: "https://intermatwrestle.com/articles/rss",         sport: "wrestling",  divisions: ["DI","DII","DIII","NAIA"] },
  { id: "row2k",             name: "Row2k",               url: "https://www.row2k.com/rss/news.xml",               sport: "rowing",     divisions: ["DI","DII","DIII"] },
  { id: "ustfccca",          name: "USTFCCCA",            url: "https://www.ustfccca.org/feed",                    sport: "track",      divisions: ["DI","DII","DIII","NAIA"] },
  { id: "volleyballmag",     name: "Volleyball Magazine", url: "https://volleyballmag.com/feed/",                  sport: "volleyball", divisions: ["DI","DII","DIII","NAIA"] },
  { id: "ncaa_news",         name: "NCAA News",           url: "https://www.ncaa.org/rss/news",                    sport: "multiple",   divisions: ["DI","DII","DIII"] },
];

const SCHOOL_DOMAINS = [
  { name: "American University",                 domain: "aueagles.com" },
  { name: "Appalachian State University",        domain: "appstatesports.com" },
  { name: "Arizona State University",            domain: "thesundevils.com" },
  { name: "Arkansas State University",           domain: "astateredwolves.com" },
  { name: "Auburn University",                   domain: "auburntigers.com" },
  { name: "Ball State University",               domain: "ballstatesports.com" },
  { name: "Baylor University",                   domain: "baylorbears.com" },
  { name: "Binghamton University",               domain: "bubearcats.com" },
  { name: "Boise State University",              domain: "broncosports.com" },
  { name: "Boston College",                      domain: "bceagles.com" },
  { name: "Boston University",                   domain: "goterriers.com" },
  { name: "Bowling Green State University",      domain: "bgsufalcons.com" },
  { name: "Brigham Young University",            domain: "byucougars.com" },
  { name: "Brown University",                    domain: "brownbears.com" },
  { name: "Bryant University",                   domain: "bryantbulldogs.com" },
  { name: "Bucknell University",                 domain: "bucknellbison.com" },
  { name: "Butler University",                   domain: "butlersports.com" },
  { name: "Cal Poly SLO",                        domain: "gopoly.com" },
  { name: "Cal State Bakersfield",               domain: "gorunners.com" },
  { name: "Cal State Fresno",                    domain: "gobulldogs.com" },
  { name: "Cal State Fullerton",                 domain: "fullertontitans.com" },
  { name: "Cal State Long Beach",                domain: "longbeachstate.com" },
  { name: "Cal State Northridge",                domain: "gomatadors.com" },
  { name: "Cal State Sacramento",                domain: "hornetsports.com" },
  { name: "Campbell University",                 domain: "gocamels.com" },
  { name: "Canisius University",                 domain: "gogriffs.com" },
  { name: "Central Connecticut State",           domain: "ccsubluedevils.com" },
  { name: "Central Michigan University",         domain: "cmuchippewas.com" },
  { name: "Charleston Southern University",      domain: "csusports.com" },
  { name: "Clemson University",                  domain: "clemsontigers.com" },
  { name: "Cleveland State University",          domain: "csuvikings.com" },
  { name: "Coastal Carolina University",         domain: "goccusports.com" },
  { name: "Colgate University",                  domain: "gocolgateraiders.com" },
  { name: "College of Charleston",               domain: "cofcsports.com" },
  { name: "College of the Holy Cross",           domain: "goholycross.com" },
  { name: "Colorado State University",           domain: "csurams.com" },
  { name: "Columbia University",                 domain: "gocolumbialions.com" },
  { name: "Coppin State University",             domain: "coppinstatesports.com" },
  { name: "Cornell University",                  domain: "cornellbigred.com" },
  { name: "Creighton University",                domain: "gocreighton.com" },
  { name: "Dartmouth College",                   domain: "dartmouthsports.com" },
  { name: "Davidson College",                    domain: "davidsonwildcats.com" },
  { name: "DePaul University",                   domain: "depaulbluedemons.com" },
  { name: "Delaware State University",           domain: "dsuhornets.com" },
  { name: "Drexel University",                   domain: "drexeldragons.com" },
  { name: "Duke University",                     domain: "goduke.com" },
  { name: "Duquesne University",                 domain: "goduquesne.com" },
  { name: "East Carolina University",            domain: "ecupirates.com" },
  { name: "East Tennessee State University",     domain: "etsubucs.com" },
  { name: "Eastern Illinois University",         domain: "eiupanthers.com" },
  { name: "Eastern Kentucky University",         domain: "ekusports.com" },
  { name: "Eastern Michigan University",         domain: "emueagles.com" },
  { name: "Eastern Washington University",       domain: "ewueagles.com" },
  { name: "Elon University",                     domain: "elonphoenix.com" },
  { name: "Fairfield University",                domain: "fairfieldstags.com" },
  { name: "Fairleigh Dickinson University",      domain: "fduknights.com" },
  { name: "Florida A&M University",              domain: "famuathletics.com" },
  { name: "Florida Atlantic University",         domain: "fausports.com" },
  { name: "Florida Gulf Coast University",       domain: "fgcuathletics.com" },
  { name: "Florida International University",    domain: "fiusports.com" },
  { name: "Florida State University",            domain: "seminoles.com" },
  { name: "Fordham University",                  domain: "fordhamsports.com" },
  { name: "Furman University",                   domain: "furmanpaladins.com" },
  { name: "Gardner-Webb University",             domain: "gwusports.com" },
  { name: "George Mason University",             domain: "gomason.com" },
  { name: "George Washington University",        domain: "gwsports.com" },
  { name: "Georgetown University",               domain: "guhoyas.com" },
  { name: "Georgia Tech",                        domain: "ramblinwreck.com" },
  { name: "Georgia Southern University",         domain: "georgiasoutherneagles.com" },
  { name: "Georgia State University",            domain: "georgiastatesports.com" },
  { name: "Gonzaga University",                  domain: "gozags.com" },
  { name: "Grambling State University",          domain: "gsutigers.com" },
  { name: "Hampton University",                  domain: "hamptonpirates.com" },
  { name: "Harvard University",                  domain: "gocrimson.com" },
  { name: "High Point University",               domain: "highpointathletics.com" },
  { name: "Hofstra University",                  domain: "hofstrapride.com" },
  { name: "Howard University",                   domain: "hubison.com" },
  { name: "Idaho State University",              domain: "isubengals.com" },
  { name: "Illinois State University",           domain: "goredbirds.com" },
  { name: "Indiana State University",            domain: "gosycamores.com" },
  { name: "Indiana University",                  domain: "iuhoosiers.com" },
  { name: "Iona University",                     domain: "icgaels.com" },
  { name: "Iowa State University",               domain: "cyclones.com" },
  { name: "Jackson State University",            domain: "jsusports.net" },
  { name: "Jacksonville State University",       domain: "jsugamecocksports.com" },
  { name: "Jacksonville University",             domain: "judolphins.com" },
  { name: "James Madison University",            domain: "jmusports.com" },
  { name: "Kansas State University",             domain: "kstatesports.com" },
  { name: "Kennesaw State University",           domain: "ksusports.com" },
  { name: "Kent State University",               domain: "kentstatesports.com" },
  { name: "La Salle University",                 domain: "goexplorers.com" },
  { name: "Lafayette College",                   domain: "goleopards.com" },
  { name: "Lamar University",                    domain: "lamarcardinals.com" },
  { name: "Lehigh University",                   domain: "lehighsports.com" },
  { name: "Liberty University",                  domain: "libertyflames.com" },
  { name: "Long Island University",              domain: "liuathletics.com" },
  { name: "Louisiana State University",          domain: "lsusports.net" },
  { name: "Louisiana Tech University",           domain: "latechsports.com" },
  { name: "Loyola Marymount University",         domain: "lmulions.com" },
  { name: "Loyola University Chicago",           domain: "loyolaramblers.com" },
  { name: "Loyola University Maryland",          domain: "loyolahounds.com" },
  { name: "Manhattan University",                domain: "manhattanjaspers.com" },
  { name: "Marist College",                      domain: "goredfoxes.com" },
  { name: "Marshall University",                 domain: "herdzone.com" },
  { name: "McNeese State University",            domain: "mcneesesports.com" },
  { name: "University of Memphis",               domain: "gotigersgo.com" },
  { name: "Mercer University",                   domain: "mercerbears.com" },
  { name: "Miami University Ohio",               domain: "muredhawks.com" },
  { name: "Michigan State University",           domain: "msuspartans.com" },
  { name: "Middle Tennessee State",              domain: "goblueraiders.com" },
  { name: "Mississippi State University",        domain: "hailstate.com" },
  { name: "Missouri State University",           domain: "missouristatebears.com" },
  { name: "Monmouth University",                 domain: "monmouthhawks.com" },
  { name: "Montana State University",            domain: "msubobcats.com" },
  { name: "Morgan State University",             domain: "morganstatebears.com" },
  { name: "Mount St. Mary's University",         domain: "mountathletics.com" },
  { name: "Murray State University",             domain: "goracers.com" },
  { name: "Navy",                                domain: "navysports.com" },
  { name: "New Mexico State University",         domain: "nmstatesports.com" },
  { name: "Niagara University",                  domain: "purpleeagles.com" },
  { name: "Nicholls State University",           domain: "nicholls.edu" },
  { name: "Norfolk State University",            domain: "nsuspartans.com" },
  { name: "North Carolina A&T",                  domain: "ncataggies.com" },
  { name: "North Carolina Central University",   domain: "ncceagles.com" },
  { name: "NC State University",                 domain: "gopack.com" },
  { name: "North Dakota State University",       domain: "gobison.com" },
  { name: "Northeastern University",             domain: "nuhuskies.com" },
  { name: "Northern Arizona University",         domain: "nauathletics.com" },
  { name: "Northern Colorado University",        domain: "uncbears.com" },
  { name: "Northern Illinois University",        domain: "niuhuskies.com" },
  { name: "Northern Iowa University",            domain: "unipanthers.com" },
  { name: "Northwestern State University",       domain: "nsudemons.com" },
  { name: "Northwestern University",             domain: "nusports.com" },
  { name: "Ohio University",                     domain: "ohiobobcats.com" },
  { name: "Ohio State University",               domain: "ohiostatebuckeyes.com" },
  { name: "Oklahoma State University",           domain: "okstate.com" },
  { name: "Old Dominion University",             domain: "odusports.com" },
  { name: "Oregon State University",             domain: "osubeavers.com" },
  { name: "Penn State University",               domain: "gopsusports.com" },
  { name: "Pepperdine University",               domain: "pepperdinesports.com" },
  { name: "University of Pittsburgh",            domain: "pittPanthers.com" },
  { name: "Portland State University",           domain: "goviks.com" },
  { name: "Prairie View A&M University",         domain: "pvpanthers.com" },
  { name: "Princeton University",                domain: "goprincetontigers.com" },
  { name: "Providence College",                  domain: "friars.com" },
  { name: "Purdue University",                   domain: "purduesports.com" },
  { name: "Quinnipiac University",               domain: "quinnipiacbobcats.com" },
  { name: "Radford University",                  domain: "radfordathletics.com" },
  { name: "University of Rhode Island",          domain: "gorhody.com" },
  { name: "Rice University",                     domain: "riceowls.com" },
  { name: "Rider University",                    domain: "riderathletics.com" },
  { name: "Robert Morris University",            domain: "rmucolonials.com" },
  { name: "Rutgers University",                  domain: "scarletknights.com" },
  { name: "Sacred Heart University",             domain: "sacredheartpioneers.com" },
  { name: "Saint Francis University",            domain: "sfuathletics.com" },
  { name: "Saint Joseph's University",           domain: "sjuhawks.com" },
  { name: "Saint Louis University",              domain: "slubillikens.com" },
  { name: "Saint Mary's College",                domain: "smcgaels.com" },
  { name: "Saint Peter's University",            domain: "saintpeterspeacocks.com" },
  { name: "Sam Houston State University",        domain: "samhoustonstatesports.com" },
  { name: "San Diego State University",          domain: "goaztecs.com" },
  { name: "San Jose State University",           domain: "sjsuspartans.com" },
  { name: "Santa Clara University",              domain: "santaclarabroncos.com" },
  { name: "Seattle University",                  domain: "seattleuathletics.com" },
  { name: "Seton Hall University",               domain: "shupirates.com" },
  { name: "Siena College",                       domain: "sienasaints.com" },
  { name: "South Carolina State University",     domain: "scstatesports.com" },
  { name: "South Dakota State University",       domain: "gojacks.com" },
  { name: "Southeast Missouri State University", domain: "gosoutheast.com" },
  { name: "Southeastern Louisiana University",   domain: "lionsports.net" },
  { name: "Southern Illinois University",        domain: "siusalukis.com" },
  { name: "Southern Methodist University",       domain: "smumustangs.com" },
  { name: "Southern Mississippi University",     domain: "southernmiss.com" },
  { name: "Southern University",                 domain: "gojagsports.com" },
  { name: "Stephen F. Austin State University",  domain: "sfajacks.com" },
  { name: "Stony Brook University",              domain: "stonybrookathletics.com" },
  { name: "Temple University",                   domain: "owlsports.com" },
  { name: "Tennessee State University",          domain: "tsutiger.com" },
  { name: "Tennessee Tech University",           domain: "ttusports.com" },
  { name: "Texas A&M University",                domain: "12thman.com" },
  { name: "Texas Southern University",           domain: "tsusports.com" },
  { name: "Texas State University",              domain: "txstatebobcats.com" },
  { name: "Texas Tech University",               domain: "texastech.com" },
  { name: "The Citadel",                         domain: "citadelsports.com" },
  { name: "Towson University",                   domain: "towsontigers.com" },
  { name: "Troy University",                     domain: "troytrojans.com" },
  { name: "Tulane University",                   domain: "tulanegreenwave.com" },
  { name: "University of Tulsa",                 domain: "tulsahurricane.com" },
  { name: "UC Davis",                            domain: "ucdavisaggies.com" },
  { name: "UC Irvine",                           domain: "ucirvinesports.com" },
  { name: "UC Riverside",                        domain: "gohighlanders.com" },
  { name: "UC San Diego",                        domain: "ucsdtritons.com" },
  { name: "UC Santa Barbara",                    domain: "ucsbgauchos.com" },
  { name: "UMass Amherst",                       domain: "umassathletics.com" },
  { name: "UMass Lowell",                        domain: "riverhawksports.com" },
  { name: "UNLV",                                domain: "unlvrebels.com" },
  { name: "UT Arlington",                        domain: "utamavericks.com" },
  { name: "UT Martin",                           domain: "utmsports.com" },
  { name: "UT Rio Grande Valley",                domain: "utrgvathletics.com" },
  { name: "Utah State University",               domain: "utahstateaggies.com" },
  { name: "Utah Valley University",              domain: "wolverinegreen.com" },
  { name: "Valparaiso University",               domain: "valpoathletics.com" },
  { name: "Villanova University",                domain: "villanova.com" },
  { name: "Virginia Commonwealth University",    domain: "vcuathletics.com" },
  { name: "Virginia Military Institute",         domain: "vmisports.com" },
  { name: "Virginia Tech",                       domain: "hokiesports.com" },
  { name: "Wagner College",                      domain: "wagnerathletics.com" },
  { name: "Wake Forest University",              domain: "deaconssports.com" },
  { name: "Washington State University",         domain: "wsucougars.com" },
  { name: "Weber State University",              domain: "weberstatewildcats.com" },
  { name: "West Virginia University",            domain: "wvusports.com" },
  { name: "Western Carolina University",         domain: "catamountsports.com" },
  { name: "Western Illinois University",         domain: "leathernecksports.com" },
  { name: "Western Kentucky University",         domain: "wkusports.com" },
  { name: "Western Michigan University",         domain: "wmubroncos.com" },
  { name: "Wichita State University",            domain: "goshockers.com" },
  { name: "William & Mary",                      domain: "tribeathletics.com" },
  { name: "Winthrop University",                 domain: "winthropeagles.com" },
  { name: "Wisconsin-Milwaukee",                 domain: "mkepanthers.com" },
  { name: "Wofford College",                     domain: "woffordterriers.com" },
  { name: "Wright State University",             domain: "wsuraiders.com" },
  { name: "University of Wyoming",               domain: "gowyo.com" },
  { name: "Xavier University",                   domain: "goxavier.com" },
  { name: "Yale University",                     domain: "yalebulldogs.com" },
  { name: "Youngstown State University",         domain: "ysupenguin.com" },
];

const RSS_PATHS = [
  { suffix: "sidearm",   path: "/rss.aspx" },
  { suffix: "sidearm2",  path: "/rss_feeds.aspx" },
  { suffix: "presto",    path: "/news/rss.xml" },
  { suffix: "rss",       path: "/rss" },
  { suffix: "feed",      path: "/feed" },
  { suffix: "newsfeed",  path: "/news/feed" },
];

const SCHOOL_SOURCES = SCHOOL_DOMAINS.flatMap(s =>
  RSS_PATHS.map(({ suffix, path }) => ({
    id: `school_${s.domain.replace(/\./g,'_')}_${suffix}`,
    name: s.name,
    url: `https://${s.domain}${path}`,
    school: s.name,
    domain: s.domain,
    type: "school"
  }))
);

module.exports = { TRADE_SOURCES, SCHOOL_SOURCES, SCHOOL_DOMAINS };
