const TRADE_SOURCES = [
  { id: "footballscoop",     name: "FootballScoop",       url: "https://footballscoop.com/feed/",                  sport: "football",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "on3",               name: "On3 Sports",          url: "https://www.on3.com/feed/",                        sport: "multiple",   divisions: ["DI"] },
  { id: "swimswam",          name: "SwimSwam",            url: "https://swimswam.com/feed/",                       sport: "swimming",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "d1baseball",        name: "D1Baseball",          url: "https://d1baseball.com/feed/",                     sport: "baseball",   divisions: ["DI"] },
  { id: "d1softball",        name: "D1Softball",          url: "https://d1softball.com/feed/",                     sport: "softball",   divisions: ["DI"] },
  { id: "nfca",              name: "NFCA",                url: "https://nfca.org/feed",                            sport: "softball",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "laxallstars",       name: "Lax All Stars",       url: "https://laxallstars.com/feed",                     sport: "lacrosse",   divisions: ["DI","DII","DIII","NAIA"] },
  { id: "collegehockeynews", name: "College Hockey News", url: "https://www.collegehockeynews.com/rss/",           sport: "hockey",     divisions: ["DI","DII","DIII"] },
  { id: "topdrawersoccer",   name: "TopDrawer Soccer",    url: "https://www.topdrawersoccer.com/rss",              sport: "soccer",     divisions: ["DI","DII","DIII","NAIA"] },
  { id: "intermatwrestle",   name: "InterMat Wrestling",  url: "https://intermatwrestle.com/articles/rss",         sport: "wrestling",  divisions: ["DI","DII","DIII","NAIA"] },
  { id: "row2k",             name: "Row2k",               url: "https://www.row2k.com/rss/news.xml",               sport: "rowing",     divisions: ["DI","DII","DIII"] },
  { id: "ustfccca",          name: "USTFCCCA",            url: "https://www.ustfccca.org/feed",                    sport: "track",      divisions: ["DI","DII","DIII","NAIA"] },
  { id: "volleyballmag",     name: "Volleyball Magazine", url: "https://volleyballmag.com/feed/",                  sport: "volleyball", divisions: ["DI","DII","DIII","NAIA"] },
  { id: "ncaa_news",         name: "NCAA News",           url: "https://www.ncaa.org/rss/news",                    sport: "multiple",   divisions: ["DI","DII","DIII"] },
  { id: "espn_top",        name: "ESPN",                    url: "https://www.espn.com/espn/rss/news",                         sport: "multiple",   divisions: ["DI"] },
  { id: "espn_ncaaf",      name: "ESPN College Football",   url: "https://www.espn.com/espn/rss/ncf/news",                     sport: "football",   divisions: ["DI"] },
  { id: "espn_ncaab",      name: "ESPN College Basketball", url: "https://www.espn.com/espn/rss/ncb/news",                     sport: "basketball", divisions: ["DI"] },
  { id: "espn_ncaaw",      name: "ESPN Women's Basketball", url: "https://www.espn.com/espn/rss/ncw/news",                     sport: "basketball", divisions: ["DI"] },
  { id: "espn_college",    name: "ESPN College Sports",     url: "https://www.espn.com/espn/rss/college-sports/news",          sport: "multiple",   divisions: ["DI"] },
  { id: "ncaa_football",        name: "NCAA Football News",          url: "https://www.ncaa.com/news/football/fbs/rss.xml",              sport: "football",   divisions: ["DI"] },
  { id: "ncaa_football_fcs",    name: "NCAA Football FCS",           url: "https://www.ncaa.com/news/football/fcs/rss.xml",              sport: "football",   divisions: ["DI"] },
  { id: "ncaa_football_d2",     name: "NCAA Football DII",           url: "https://www.ncaa.com/news/football/d2/rss.xml",               sport: "football",   divisions: ["DII"] },
  { id: "ncaa_football_d3",     name: "NCAA Football DIII",          url: "https://www.ncaa.com/news/football/d3/rss.xml",               sport: "football",   divisions: ["DIII"] },
  { id: "ncaa_mbball_d1",       name: "NCAA Men's Basketball DI",    url: "https://www.ncaa.com/news/basketball-men/d1/rss.xml",         sport: "basketball", divisions: ["DI"] },
  { id: "ncaa_mbball_d2",       name: "NCAA Men's Basketball DII",   url: "https://www.ncaa.com/news/basketball-men/d2/rss.xml",         sport: "basketball", divisions: ["DII"] },
  { id: "ncaa_mbball_d3",       name: "NCAA Men's Basketball DIII",  url: "https://www.ncaa.com/news/basketball-men/d3/rss.xml",         sport: "basketball", divisions: ["DIII"] },
  { id: "ncaa_wbball_d1",       name: "NCAA Women's Basketball DI",  url: "https://www.ncaa.com/news/basketball-women/d1/rss.xml",       sport: "basketball", divisions: ["DI"] },
  { id: "ncaa_wbball_d2",       name: "NCAA Women's Basketball DII", url: "https://www.ncaa.com/news/basketball-women/d2/rss.xml",       sport: "basketball", divisions: ["DII"] },
  { id: "ncaa_wbball_d3",       name: "NCAA Women's Basketball DIII",url: "https://www.ncaa.com/news/basketball-women/d3/rss.xml",       sport: "basketball", divisions: ["DIII"] },
  { id: "ncaa_baseball_d1",     name: "NCAA Baseball DI",            url: "https://www.ncaa.com/news/baseball/d1/rss.xml",               sport: "baseball",   divisions: ["DI"] },
  { id: "ncaa_baseball_d2",     name: "NCAA Baseball DII",           url: "https://www.ncaa.com/news/baseball/d2/rss.xml",               sport: "baseball",   divisions: ["DII"] },
  { id: "ncaa_baseball_d3",     name: "NCAA Baseball DIII",          url: "https://www.ncaa.com/news/baseball/d3/rss.xml",               sport: "baseball",   divisions: ["DIII"] },
  { id: "ncaa_softball_d1",     name: "NCAA Softball DI",            url: "https://www.ncaa.com/news/softball/d1/rss.xml",               sport: "softball",   divisions: ["DI"] },
  { id: "ncaa_softball_d2",     name: "NCAA Softball DII",           url: "https://www.ncaa.com/news/softball/d2/rss.xml",               sport: "softball",   divisions: ["DII"] },
  { id: "ncaa_softball_d3",     name: "NCAA Softball DIII",          url: "https://www.ncaa.com/news/softball/d3/rss.xml",               sport: "softball",   divisions: ["DIII"] },
  { id: "ncaa_soccer_m_d1",     name: "NCAA Men's Soccer DI",        url: "https://www.ncaa.com/news/soccer-men/d1/rss.xml",             sport: "soccer",     divisions: ["DI"] },
  { id: "ncaa_soccer_w_d1",     name: "NCAA Women's Soccer DI",      url: "https://www.ncaa.com/news/soccer-women/d1/rss.xml",           sport: "soccer",     divisions: ["DI"] },
  { id: "ncaa_swim_m_d1",       name: "NCAA Men's Swimming DI",      url: "https://www.ncaa.com/news/swimming-men/d1/rss.xml",           sport: "swimming",   divisions: ["DI"] },
  { id: "ncaa_swim_w_d1",       name: "NCAA Women's Swimming DI",    url: "https://www.ncaa.com/news/swimming-women/d1/rss.xml",         sport: "swimming",   divisions: ["DI"] },
  { id: "ncaa_track_m_d1",      name: "NCAA Men's Track DI",         url: "https://www.ncaa.com/news/trackfield-outdoor-men/d1/rss.xml", sport: "track",      divisions: ["DI"] },
  { id: "ncaa_track_w_d1",      name: "NCAA Women's Track DI",       url: "https://www.ncaa.com/news/trackfield-outdoor-women/d1/rss.xml",sport: "track",     divisions: ["DI"] },
  { id: "ncaa_volleyball_d1",   name: "NCAA Volleyball DI",          url: "https://www.ncaa.com/news/volleyball-women/d1/rss.xml",       sport: "volleyball", divisions: ["DI"] },
  { id: "ncaa_lacrosse_m_d1",   name: "NCAA Men's Lacrosse DI",      url: "https://www.ncaa.com/news/lacrosse-men/d1/rss.xml",           sport: "lacrosse",   divisions: ["DI"] },
  { id: "ncaa_lacrosse_w_d1",   name: "NCAA Women's Lacrosse DI",    url: "https://www.ncaa.com/news/lacrosse-women/d1/rss.xml",         sport: "lacrosse",   divisions: ["DI"] },
  { id: "ncaa_hockey_m_d1",     name: "NCAA Men's Hockey DI",        url: "https://www.ncaa.com/news/icehockey-men/d1/rss.xml",          sport: "hockey",     divisions: ["DI"] },
  { id: "ncaa_wrestling_d1",    name: "NCAA Wrestling DI",           url: "https://www.ncaa.com/news/wrestling-men/d1/rss.xml",          sport: "wrestling",  divisions: ["DI"] },
  { id: "ncaa_rowing_d1",       name: "NCAA Rowing DI",              url: "https://www.ncaa.com/news/rowing/d1/rss.xml",                 sport: "rowing",     divisions: ["DI"] },
  { id: "ncaa_gymnastics_w_d1", name: "NCAA Women's Gymnastics DI",  url: "https://www.ncaa.com/news/gymnastics-women/d1/rss.xml",       sport: "gymnastics", divisions: ["DI"] },
  { id: "ncaa_tennis_m_d1",     name: "NCAA Men's Tennis DI",        url: "https://www.ncaa.com/news/tennis-men/d1/rss.xml",             sport: "tennis",     divisions: ["DI"] },
  { id: "ncaa_tennis_w_d1",     name: "NCAA Women's Tennis DI",      url: "https://www.ncaa.com/news/tennis-women/d1/rss.xml",           sport: "tennis",     divisions: ["DI"] },
  { id: "espn_top",             name: "ESPN",                         url: "https://www.espn.com/espn/rss/news",                         sport: "multiple",   divisions: ["DI"] },
  { id: "espn_ncaaf",           name: "ESPN College Football",        url: "https://www.espn.com/espn/rss/ncf/news",                     sport: "football",   divisions: ["DI"] },
  { id: "espn_ncaab",           name: "ESPN College Basketball",      url: "https://www.espn.com/espn/rss/ncb/news",                     sport: "basketball", divisions: ["DI"] },
  { id: "espn_ncaaw",           name: "ESPN Women's Basketball",      url: "https://www.espn.com/espn/rss/ncw/news",                     sport: "basketball", divisions: ["DI"] },
  { id: "yahoo_ncaaf",   name: "Yahoo College Football",      url: "https://sports.yahoo.com/college-football/rss/",      sport: "football",   divisions: ["DI"] },
  { id: "yahoo_ncaab",   name: "Yahoo College Basketball",    url: "https://sports.yahoo.com/college-basketball/rss/",    sport: "basketball", divisions: ["DI"] },
  { id: "yahoo_ncaaw",   name: "Yahoo Women's Basketball",    url: "https://sports.yahoo.com/womens-college-basketball/rss/", sport: "basketball", divisions: ["DI"] },
  { id: "yahoo_ncaab2",  name: "Yahoo College Baseball",      url: "https://sports.yahoo.com/college-baseball/rss/",      sport: "baseball",   divisions: ["DI"] },
  { id: "yahoo_sports",  name: "Yahoo Sports",                url: "https://sports.yahoo.com/rss/",                       sport: "multiple",   divisions: ["DI"] },
  { id: "d2football",       name: "D2Football.com",        url: "https://www.d2football.com/feed/",                   sport: "football",   divisions: ["DII"] },
  { id: "d2football_news",  name: "D2Football News",        url: "https://www.d2football.com/front-page-news/feed/",   sport: "football",   divisions: ["DII"] },
  // Power Four conferences
  { id: "conf_acc",        name: "ACC",               url: "https://theacc.com/rss.aspx",                  sport: "multiple", divisions: ["DI"] },
  { id: "conf_big10",      name: "Big Ten",            url: "https://bigten.org/rss.aspx",                  sport: "multiple", divisions: ["DI"] },
  { id: "conf_big12",      name: "Big 12",             url: "https://big12sports.com/rss.aspx",             sport: "multiple", divisions: ["DI"] },
  { id: "conf_sec",        name: "SEC",                url: "https://secsports.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },

  // Group of Five
  { id: "conf_american",   name: "American Athletic",  url: "https://theamerican.org/rss.aspx",             sport: "multiple", divisions: ["DI"] },
  { id: "conf_cusa",       name: "Conference USA",     url: "https://conferenceusa.com/rss.aspx",           sport: "multiple", divisions: ["DI"] },
  { id: "conf_mac",        name: "MAC",                url: "https://getsomemaction.com/rss.aspx",          sport: "multiple", divisions: ["DI"] },
  { id: "conf_mw",         name: "Mountain West",      url: "https://themw.com/rss.aspx",                   sport: "multiple", divisions: ["DI"] },
  { id: "conf_sunbelt",    name: "Sun Belt",           url: "https://sunbeltsports.org/rss.aspx",           sport: "multiple", divisions: ["DI"] },

  // FCS / Mid-Major DI
  { id: "conf_bigsky",     name: "Big Sky",            url: "https://bigskyconf.com/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_bigsouth",   name: "Big South",          url: "https://bigsouthsports.com/rss.aspx",          sport: "multiple", divisions: ["DI"] },
  { id: "conf_caa",        name: "CAA",                url: "https://caasports.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  { id: "conf_ivy",        name: "Ivy League",         url: "https://ivyleague.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  { id: "conf_meac",       name: "MEAC",               url: "https://meacsports.com/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_mvc",        name: "Missouri Valley",    url: "https://mvc-sports.com/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_nec",        name: "Northeast Conference",url: "https://northeastconference.org/rss.aspx",    sport: "multiple", divisions: ["DI"] },
  { id: "conf_ovc",        name: "Ohio Valley",        url: "https://ovcsports.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  { id: "conf_patriot",    name: "Patriot League",     url: "https://patriotleague.org/rss.aspx",           sport: "multiple", divisions: ["DI"] },
  { id: "conf_socon",      name: "Southern Conference", url: "https://soconsports.com/rss.aspx",            sport: "multiple", divisions: ["DI"] },
  { id: "conf_southland",  name: "Southland",          url: "https://southland.org/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  { id: "conf_swac",       name: "SWAC",               url: "https://swac.org/rss.aspx",                    sport: "multiple", divisions: ["DI"] },

  // Non-football DI
  { id: "conf_americaeast",name: "America East",       url: "https://americaeast.com/rss.aspx",             sport: "multiple", divisions: ["DI"] },
  { id: "conf_asun",       name: "ASUN",               url: "https://asunsports.org/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_atlantic10", name: "Atlantic 10",        url: "https://atlantic10.com/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_bigeast",    name: "Big East",           url: "https://bigeast.com/rss.aspx",                 sport: "multiple", divisions: ["DI"] },
  { id: "conf_bigwest",    name: "Big West",           url: "https://bigwest.org/rss.aspx",                 sport: "multiple", divisions: ["DI"] },
  { id: "conf_horizon",    name: "Horizon League",     url: "https://horizonleague.org/rss.aspx",           sport: "multiple", divisions: ["DI"] },
  { id: "conf_maac",       name: "MAAC",               url: "https://maacsports.com/rss.aspx",              sport: "multiple", divisions: ["DI"] },
  { id: "conf_summit",     name: "Summit League",      url: "https://thesummitleague.org/rss.aspx",         sport: "multiple", divisions: ["DI"] },
  { id: "conf_wcc",        name: "West Coast",         url: "https://wccsports.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  { id: "conf_wac",        name: "WAC",                url: "https://wacsports.com/rss.aspx",               sport: "multiple", divisions: ["DI"] },
  // DII conferences
  { id: "conf_ccaa",       name: "CCAA",                url: "https://goccaa.org/rss.aspx",                       sport: "multiple", divisions: ["DII"] },
  { id: "conf_cacc",       name: "CACC",                url: "https://caccathletics.org/rss.aspx",                sport: "multiple", divisions: ["DII"] },
  { id: "conf_ciaa",       name: "CIAA",                url: "https://theciaa.com/rss.aspx",                      sport: "multiple", divisions: ["DII"] },
  { id: "conf_carolinas",  name: "Conference Carolinas", url: "https://conferencecarolinas.com/rss.aspx",         sport: "multiple", divisions: ["DII"] },
  { id: "conf_ecc",        name: "East Coast Conference", url: "https://eccsports.org/rss.aspx",                  sport: "multiple", divisions: ["DII"] },
  { id: "conf_gliac",      name: "GLIAC",               url: "https://gliac.org/rss.aspx",                        sport: "multiple", divisions: ["DII"] },
  { id: "conf_glvc",       name: "GLVC",                url: "https://glvcsports.com/rss.aspx",                   sport: "multiple", divisions: ["DII"] },
  { id: "conf_gmac",       name: "G-MAC",               url: "https://greatmidwestsports.com/rss.aspx",           sport: "multiple", divisions: ["DII"] },
  { id: "conf_gac",        name: "Great American",      url: "https://greatamericanconference.com/rss.aspx",      sport: "multiple", divisions: ["DII"] },
  { id: "conf_gnac",       name: "GNAC",                url: "https://gnacsports.com/news/rss/",                  sport: "multiple", divisions: ["DII"] },
  { id: "conf_lsc",        name: "Lone Star",           url: "https://lonestarconference.org/rss.aspx",           sport: "multiple", divisions: ["DII"] },
  { id: "conf_miaa",       name: "MIAA",                url: "https://themiaa.com/rss.aspx",                      sport: "multiple", divisions: ["DII"] },
  { id: "conf_nsic",       name: "NSIC",                url: "https://northernsun.org/rss.aspx",                  sport: "multiple", divisions: ["DII"] },
  { id: "conf_rmac",       name: "RMAC",                url: "https://rmacsports.org/rss.aspx",                   sport: "multiple", divisions: ["DII"] },
  { id: "conf_ne10",       name: "NE10",                url: "https://northeast10.org/rss.aspx",                  sport: "multiple", divisions: ["DII"] },
  { id: "conf_psac",       name: "PSAC",                url: "https://psacsports.org/rss.aspx",                   sport: "multiple", divisions: ["DII"] },
  { id: "conf_mec",        name: "Mountain East",       url: "https://mountaineast.org/rss.aspx",                 sport: "multiple", divisions: ["DII"] },
  { id: "conf_gsc",        name: "Gulf South",          url: "https://gscsports.org/rss.aspx",                    sport: "multiple", divisions: ["DII"] },
  { id: "conf_sac",        name: "South Atlantic",      url: "https://thesac.com/rss.aspx",                       sport: "multiple", divisions: ["DII"] },
  { id: "conf_siac",       name: "SIAC",                url: "https://thesiac.com/rss.aspx",                      sport: "multiple", divisions: ["DII"] },
  { id: "conf_ssc",        name: "Sunshine State",      url: "https://sunshinestateconference.com/rss.aspx",      sport: "multiple", divisions: ["DII"] },
  { id: "conf_peachbelt",  name: "Peach Belt",          url: "https://peachbeltconference.org/rss.aspx",          sport: "multiple", divisions: ["DII"] },
  // DIII conferences — New England
  { id: "d3_arc",          name: "American Rivers",        url: "https://rollrivers.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_ccc",          name: "Commonwealth Coast",     url: "https://cccathletics.com/rss.aspx",                sport: "multiple", divisions: ["DIII"] },
  { id: "d3_lec",          name: "Little East",            url: "https://littleeast.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_mascac",       name: "MASCAC",                 url: "https://mascac.com/rss.aspx",                      sport: "multiple", divisions: ["DIII"] },
  { id: "d3_newmac",       name: "NEWMAC",                 url: "https://newmacsports.com/rss.aspx",                sport: "multiple", divisions: ["DIII"] },
  { id: "d3_nescac",       name: "NESCAC",                 url: "https://nescac.com/rss.aspx",                      sport: "multiple", divisions: ["DIII"] },
  { id: "d3_nac",          name: "North Atlantic",         url: "https://nacathletics.com/rss.aspx",                sport: "multiple", divisions: ["DIII"] },

  // DIII conferences — Mid-Atlantic
  { id: "d3_atleast",      name: "Atlantic East",          url: "https://atlanticeast.com/rss.aspx",                sport: "multiple", divisions: ["DIII"] },
  { id: "d3_centennial",   name: "Centennial",             url: "https://centennial.org/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_cunyac",       name: "CUNYAC",                 url: "https://cunyathletics.com/rss.aspx",               sport: "multiple", divisions: ["DIII"] },
  { id: "d3_empire8",      name: "Empire 8",               url: "https://empire8.com/rss.aspx",                     sport: "multiple", divisions: ["DIII"] },
  { id: "d3_landmark",     name: "Landmark",               url: "https://landmarkconference.org/rss.aspx",          sport: "multiple", divisions: ["DIII"] },
  { id: "d3_libertyleague",name: "Liberty League",         url: "https://libertyleagueathletics.com/rss.aspx",      sport: "multiple", divisions: ["DIII"] },
  { id: "d3_mac",          name: "MAC (DIII)",             url: "https://gomacsports.com/rss.aspx",                 sport: "multiple", divisions: ["DIII"] },
  { id: "d3_njac",         name: "NJAC",                   url: "https://njacsports.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_skyline",      name: "Skyline",                url: "https://skylineconference.org/rss.aspx",           sport: "multiple", divisions: ["DIII"] },
  { id: "d3_sunyac",       name: "SUNYAC",                 url: "https://sunyac.com/rss.aspx",                      sport: "multiple", divisions: ["DIII"] },
  { id: "d3_unitedeast",   name: "United East",            url: "https://unitedeast.org/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },

  // DIII conferences — Midwest
  { id: "d3_cciw",         name: "CCIW",                   url: "https://cciw.org/rss.aspx",                        sport: "multiple", divisions: ["DIII"] },
  { id: "d3_hcac",         name: "Heartland Collegiate",   url: "https://heartlandconf.org/rss.aspx",               sport: "multiple", divisions: ["DIII"] },
  { id: "d3_miaa",         name: "MIAA (DIII)",            url: "https://miaa.org/rss.aspx",                        sport: "multiple", divisions: ["DIII"] },
  { id: "d3_mwc",          name: "Midwest Conference",     url: "https://midwestconference.org/rss.aspx",           sport: "multiple", divisions: ["DIII"] },
  { id: "d3_ncac",         name: "North Coast Athletic",   url: "https://northcoast.org/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_nacc",         name: "NACC",                   url: "https://naccsports.org/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_oac",          name: "Ohio Athletic",          url: "https://oac.org/rss.aspx",                         sport: "multiple", divisions: ["DIII"] },
  { id: "d3_umac",         name: "UMAC",                   url: "https://umacathletics.com/rss.aspx",               sport: "multiple", divisions: ["DIII"] },
  { id: "d3_wiac",         name: "WIAC",                   url: "https://wiacsports.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },

  // DIII conferences — South
  { id: "d3_asc",          name: "American Southwest",     url: "https://ascsports.org/rss.aspx",                   sport: "multiple", divisions: ["DIII"] },
  { id: "d3_ccs",          name: "Collegiate Conference South", url: "https://ccsathletics.org/rss.aspx",           sport: "multiple", divisions: ["DIII"] },
  { id: "d3_odac",         name: "ODAC",                   url: "https://odaconline.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_saa",          name: "Southern Athletic",      url: "https://saa-sports.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_usasouth",     name: "USA South",              url: "https://usasouth.net/rss.aspx",                    sport: "multiple", divisions: ["DIII"] },

  // DIII conferences — West
  { id: "d3_nwc",          name: "Northwest Conference",   url: "https://nwcsports.com/rss.aspx",                   sport: "multiple", divisions: ["DIII"] },
  { id: "d3_sciac",        name: "SCIAC",                  url: "https://sciac.org/rss.aspx",                       sport: "multiple", divisions: ["DIII"] },
  { id: "d3_scac",         name: "SCAC",                   url: "https://scacsports.com/rss.aspx",                  sport: "multiple", divisions: ["DIII"] },
  { id: "d3_sliac",        name: "SLIAC",                  url: "https://sliac.org/rss.aspx",                       sport: "multiple", divisions: ["DIII"] },
  // NAIA conferences
  { id: "naia_aac",        name: "Appalachian Athletic",   url: "https://www.aacsports.com/rss/index",              sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_cascade",    name: "Cascade Collegiate",     url: "https://cascadeconference.org/rss.aspx",           sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_ccac",       name: "CCAC",                   url: "https://ccacsports.com/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_crossroads", name: "Crossroads League",      url: "https://crossroadsleague.com/rss-feeds",           sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_frontier",   name: "Frontier Conference",    url: "https://frontierconference.com/rss.aspx",          sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_gpac",       name: "GPAC",                   url: "https://gpacsports.com/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_haac",       name: "Heart of America",       url: "https://heartofamericaconference.com/rss.aspx",    sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_kcac",       name: "KCAC",                   url: "https://kcacsports.com/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_nsaa",       name: "North Star Athletic",    url: "https://playnorthstar.com/rss.aspx",               sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_midsouth",   name: "Mid-South Conference",   url: "https://mid-southconference.org/rss.aspx",         sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_ssac",       name: "Southern States Athletic",url: "https://ssacsports.com/rss.aspx",                 sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_sun",        name: "Sun Conference",         url: "https://thesunconference.com/rss.aspx",            sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_calpac",     name: "Cal Pac",                url: "https://calpacathletics.com/rss.aspx",             sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_gsac",       name: "GSAC",                   url: "https://gsacsports.org/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_rrac",       name: "Red River Athletic",     url: "https://rracsports.com/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_sooner",     name: "Sooner Athletic",        url: "https://soonerathletic.org/rss.aspx",              sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_cac",        name: "Continental Athletic",   url: "https://cacathletics.com/rss.aspx",                sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_whac",       name: "WHAC",                   url: "https://whacsports.com/rss.aspx",                  sport: "multiple", divisions: ["NAIA"] },
  { id: "naia_rsc",        name: "River States",           url: "https://riverstatesconference.com/rss.aspx",       sport: "multiple", divisions: ["NAIA"] },
];

const SCHOOL_DOMAINS = [
  { name: "American University",                 domain: "aueagles.com" },
  { name: "Appalachian State University",        domain: "appstatesports.com" },
  { name: "Arizona State University",            domain: "thesundevils.com" },
  { name: "Arkansas State University",           domain: "astateredwolves.com" },
  { name: "Auburn University",                   domain: "auburntigers.com" },
  { name: "Ball State University",               domain: "ballstatesports.com" },
  { name: "Baylor University",                   domain: "baylorbears.com" },
  { name: "Binghamton University",               domain: "bubearcats.com" },
  { name: "Boise State University",              domain: "broncosports.com" },
  { name: "Boston College",                      domain: "bceagles.com" },
  { name: "Boston University",                   domain: "goterriers.com" },
  { name: "Bowling Green State University",      domain: "bgsufalcons.com" },
  { name: "Brigham Young University",            domain: "byucougars.com" },
  { name: "Brown University",                    domain: "brownbears.com" },
  { name: "Bryant University",                   domain: "bryantbulldogs.com" },
  { name: "Bucknell University",                 domain: "bucknellbison.com" },
  { name: "Butler University",                   domain: "butlersports.com" },
  { name: "Cal Poly SLO",                        domain: "gopoly.com" },
  { name: "Cal State Bakersfield",               domain: "gorunners.com" },
  { name: "Cal State Fresno",                    domain: "gobulldogs.com" },
  { name: "Cal State Fullerton",                 domain: "fullertontitans.com" },
  { name: "Cal State Long Beach",                domain: "longbeachstate.com" },
  { name: "Cal State Northridge",                domain: "gomatadors.com" },
  { name: "Cal State Sacramento",                domain: "hornetsports.com" },
  { name: "Campbell University",                 domain: "gocamels.com" },
  { name: "Canisius University",                 domain: "gogriffs.com" },
  { name: "Central Connecticut State",           domain: "ccsubluedevils.com" },
  { name: "Central Michigan University",         domain: "cmuchippewas.com" },
  { name: "Charleston Southern University",      domain: "csusports.com" },
  { name: "Clemson University",                  domain: "clemsontigers.com" },
  { name: "Cleveland State University",          domain: "csuvikings.com" },
  { name: "Coastal Carolina University",         domain: "goccusports.com" },
  { name: "Colgate University",                  domain: "gocolgateraiders.com" },
  { name: "College of Charleston",               domain: "cofcsports.com" },
  { name: "College of the Holy Cross",           domain: "goholycross.com" },
  { name: "Colorado State University",           domain: "csurams.com" },
  { name: "Columbia University",                 domain: "gocolumbialions.com" },
  { name: "Coppin State University",             domain: "coppinstatesports.com" },
  { name: "Cornell University",                  domain: "cornellbigred.com" },
  { name: "Creighton University",                domain: "gocreighton.com" },
  { name: "Dartmouth College",                   domain: "dartmouthsports.com" },
  { name: "Davidson College",                    domain: "davidsonwildcats.com" },
  { name: "DePaul University",                   domain: "depaulbluedemons.com" },
  { name: "Delaware State University",           domain: "dsuhornets.com" },
  { name: "Drexel University",                   domain: "drexeldragons.com" },
  { name: "Duke University",                     domain: "goduke.com" },
  { name: "Duquesne University",                 domain: "goduquesne.com" },
  { name: "East Carolina University",            domain: "ecupirates.com" },
  { name: "East Tennessee State University",     domain: "etsubucs.com" },
  { name: "Eastern Illinois University",         domain: "eiupanthers.com" },
  { name: "Eastern Kentucky University",         domain: "ekusports.com" },
  { name: "Eastern Michigan University",         domain: "emueagles.com" },
  { name: "Eastern Washington University",       domain: "ewueagles.com" },
  { name: "Elon University",                     domain: "elonphoenix.com" },
  { name: "Fairfield University",                domain: "fairfieldstags.com" },
  { name: "Fairleigh Dickinson University",      domain: "fduknights.com" },
  { name: "Florida A&M University",              domain: "famuathletics.com" },
  { name: "Florida Atlantic University",         domain: "fausports.com" },
  { name: "Florida Gulf Coast University",       domain: "fgcuathletics.com" },
  { name: "Florida International University",    domain: "fiusports.com" },
  { name: "Florida State University",            domain: "seminoles.com" },
  { name: "Fordham University",                  domain: "fordhamsports.com" },
  { name: "Furman University",                   domain: "furmanpaladins.com" },
  { name: "Gardner-Webb University",             domain: "gwusports.com" },
  { name: "George Mason University",             domain: "gomason.com" },
  { name: "George Washington University",        domain: "gwsports.com" },
  { name: "Georgetown University",               domain: "guhoyas.com" },
  { name: "Georgia Tech",                        domain: "ramblinwreck.com" },
  { name: "Georgia Southern University",         domain: "georgiasoutherneagles.com" },
  { name: "Georgia State University",            domain: "georgiastatesports.com" },
  { name: "Gonzaga University",                  domain: "gozags.com" },
  { name: "Grambling State University",          domain: "gsutigers.com" },
  { name: "Hampton University",                  domain: "hamptonpirates.com" },
  { name: "Harvard University",                  domain: "gocrimson.com" },
  { name: "High Point University",               domain: "highpointathletics.com" },
  { name: "Hofstra University",                  domain: "hofstrapride.com" },
  { name: "Howard University",                   domain: "hubison.com" },
  { name: "Idaho State University",              domain: "isubengals.com" },
  { name: "Illinois State University",           domain: "goredbirds.com" },
  { name: "Indiana State University",            domain: "gosycamores.com" },
  { name: "Indiana University",                  domain: "iuhoosiers.com" },
  { name: "Iona University",                     domain: "icgaels.com" },
  { name: "Iowa State University",               domain: "cyclones.com" },
  { name: "Jackson State University",            domain: "jsusports.net" },
  { name: "Jacksonville State University",       domain: "jsugamecocksports.com" },
  { name: "Jacksonville University",             domain: "judolphins.com" },
  { name: "James Madison University",            domain: "jmusports.com" },
  { name: "Kansas State University",             domain: "kstatesports.com" },
  { name: "Kennesaw State University",           domain: "ksusports.com" },
  { name: "Kent State University",               domain: "kentstatesports.com" },
  { name: "La Salle University",                 domain: "goexplorers.com" },
  { name: "Lafayette College",                   domain: "goleopards.com" },
  { name: "Lamar University",                    domain: "lamarcardinals.com" },
  { name: "Lehigh University",                   domain: "lehighsports.com" },
  { name: "Liberty University",                  domain: "libertyflames.com" },
  { name: "Long Island University",              domain: "liuathletics.com" },
  { name: "Louisiana State University",          domain: "lsusports.net" },
  { name: "Louisiana Tech University",           domain: "latechsports.com" },
  { name: "Loyola Marymount University",         domain: "lmulions.com" },
  { name: "Loyola University Chicago",           domain: "loyolaramblers.com" },
  { name: "Loyola University Maryland",          domain: "loyolahounds.com" },
  { name: "Manhattan University",                domain: "manhattanjaspers.com" },
  { name: "Marist College",                      domain: "goredfoxes.com" },
  { name: "Marshall University",                 domain: "herdzone.com" },
  { name: "McNeese State University",            domain: "mcneesesports.com" },
  { name: "University of Memphis",               domain: "gotigersgo.com" },
  { name: "Mercer University",                   domain: "mercerbears.com" },
  { name: "Miami University Ohio",               domain: "muredhawks.com" },
  { name: "Michigan State University",           domain: "msuspartans.com" },
  { name: "Middle Tennessee State",              domain: "goblueraiders.com" },
  { name: "Mississippi State University",        domain: "hailstate.com" },
  { name: "Missouri State University",           domain: "missouristatebears.com" },
  { name: "Monmouth University",                 domain: "monmouthhawks.com" },
  { name: "Montana State University",            domain: "msubobcats.com" },
  { name: "Morgan State University",             domain: "morganstatebears.com" },
  { name: "Mount St. Mary's University",         domain: "mountathletics.com" },
  { name: "Murray State University",             domain: "goracers.com" },
  { name: "Navy",                                domain: "navysports.com" },
  { name: "New Mexico State University",         domain: "nmstatesports.com" },
  { name: "Niagara University",                  domain: "purpleeagles.com" },
  { name: "Nicholls State University",           domain: "nicholls.edu" },
  { name: "Norfolk State University",            domain: "nsuspartans.com" },
  { name: "North Carolina A&T",                  domain: "ncataggies.com" },
  { name: "North Carolina Central University",   domain: "ncceagles.com" },
  { name: "NC State University",                 domain: "gopack.com" },
  { name: "North Dakota State University",       domain: "gobison.com" },
  { name: "Northeastern University",             domain: "nuhuskies.com" },
  { name: "Northern Arizona University",         domain: "nauathletics.com" },
  { name: "Northern Colorado University",        domain: "uncbears.com" },
  { name: "Northern Illinois University",        domain: "niuhuskies.com" },
  { name: "Northern Iowa University",            domain: "unipanthers.com" },
  { name: "Northwestern State University",       domain: "nsudemons.com" },
  { name: "Northwestern University",             domain: "nusports.com" },
  { name: "Ohio University",                     domain: "ohiobobcats.com" },
  { name: "Ohio State University",               domain: "ohiostatebuckeyes.com" },
  { name: "Oklahoma State University",           domain: "okstate.com" },
  { name: "Old Dominion University",             domain: "odusports.com" },
  { name: "Oregon State University",             domain: "osubeavers.com" },
  { name: "Penn State University",               domain: "gopsusports.com" },
  { name: "Pepperdine University",               domain: "pepperdinesports.com" },
  { name: "University of Pittsburgh",            domain: "pittPanthers.com" },
  { name: "Portland State University",           domain: "goviks.com" },
  { name: "Prairie View A&M University",         domain: "pvpanthers.com" },
  { name: "Princeton University",                domain: "goprincetontigers.com" },
  { name: "Providence College",                  domain: "friars.com" },
  { name: "Purdue University",                   domain: "purduesports.com" },
  { name: "Quinnipiac University",               domain: "quinnipiacbobcats.com" },
  { name: "Radford University",                  domain: "radfordathletics.com" },
  { name: "University of Rhode Island",          domain: "gorhody.com" },
  { name: "Rice University",                     domain: "riceowls.com" },
  { name: "Rider University",                    domain: "riderathletics.com" },
  { name: "Robert Morris University",            domain: "rmucolonials.com" },
  { name: "Rutgers University",                  domain: "scarletknights.com" },
  { name: "Sacred Heart University",             domain: "sacredheartpioneers.com" },
  { name: "Saint Francis University",            domain: "sfuathletics.com" },
  { name: "Saint Joseph's University",           domain: "sjuhawks.com" },
  { name: "Saint Louis University",              domain: "slubillikens.com" },
  { name: "Saint Mary's College",                domain: "smcgaels.com" },
  { name: "Saint Peter's University",            domain: "saintpeterspeacocks.com" },
  { name: "Sam Houston State University",        domain: "samhoustonstatesports.com" },
  { name: "San Diego State University",          domain: "goaztecs.com" },
  { name: "San Jose State University",           domain: "sjsuspartans.com" },
  { name: "Santa Clara University",              domain: "santaclarabroncos.com" },
  { name: "Seattle University",                  domain: "seattleuathletics.com" },
  { name: "Seton Hall University",               domain: "shupirates.com" },
  { name: "Siena College",                       domain: "sienasaints.com" },
  { name: "South Carolina State University",     domain: "scstatesports.com" },
  { name: "South Dakota State University",       domain: "gojacks.com" },
  { name: "Southeast Missouri State University", domain: "gosoutheast.com" },
  { name: "Southeastern Louisiana University",   domain: "lionsports.net" },
  { name: "Southern Illinois University",        domain: "siusalukis.com" },
  { name: "Southern Methodist University",       domain: "smumustangs.com" },
  { name: "Southern Mississippi University",     domain: "southernmiss.com" },
  { name: "Southern University",                 domain: "gojagsports.com" },
  { name: "Stephen F. Austin State University",  domain: "sfajacks.com" },
  { name: "Stony Brook University",              domain: "stonybrookathletics.com" },
  { name: "Temple University",                   domain: "owlsports.com" },
  { name: "Tennessee State University",          domain: "tsutiger.com" },
  { name: "Tennessee Tech University",           domain: "ttusports.com" },
  { name: "Texas A&M University",                domain: "12thman.com" },
  { name: "Texas Southern University",           domain: "tsusports.com" },
  { name: "Texas State University",              domain: "txstatebobcats.com" },
  { name: "Texas Tech University",               domain: "texastech.com" },
  { name: "The Citadel",                         domain: "citadelsports.com" },
  { name: "Towson University",                   domain: "towsontigers.com" },
  { name: "Troy University",                     domain: "troytrojans.com" },
  { name: "Tulane University",                   domain: "tulanegreenwave.com" },
  { name: "University of Tulsa",                 domain: "tulsahurricane.com" },
  { name: "UC Davis",                            domain: "ucdavisaggies.com" },
  { name: "UC Irvine",                           domain: "ucirvinesports.com" },
  { name: "UC Riverside",                        domain: "gohighlanders.com" },
  { name: "UC San Diego",                        domain: "ucsdtritons.com" },
  { name: "UC Santa Barbara",                    domain: "ucsbgauchos.com" },
  { name: "UMass Amherst",                       domain: "umassathletics.com" },
  { name: "UMass Lowell",                        domain: "riverhawksports.com" },
  { name: "UNLV",                                domain: "unlvrebels.com" },
  { name: "UT Arlington",                        domain: "utamavericks.com" },
  { name: "UT Martin",                           domain: "utmsports.com" },
  { name: "UT Rio Grande Valley",                domain: "utrgvathletics.com" },
  { name: "Utah State University",               domain: "utahstateaggies.com" },
  { name: "Utah Valley University",              domain: "wolverinegreen.com" },
  { name: "Valparaiso University",               domain: "valpoathletics.com" },
  { name: "Villanova University",                domain: "villanova.com" },
  { name: "Virginia Commonwealth University",    domain: "vcuathletics.com" },
  { name: "Virginia Military Institute",         domain: "vmisports.com" },
  { name: "Virginia Tech",                       domain: "hokiesports.com" },
  { name: "Wagner College",                      domain: "wagnerathletics.com" },
  { name: "Wake Forest University",              domain: "deaconssports.com" },
  { name: "Washington State University",         domain: "wsucougars.com" },
  { name: "Weber State University",              domain: "weberstatewildcats.com" },
  { name: "West Virginia University",            domain: "wvusports.com" },
  { name: "Western Carolina University",         domain: "catamountsports.com" },
  { name: "Western Illinois University",         domain: "leathernecksports.com" },
  { name: "Western Kentucky University",         domain: "wkusports.com" },
  { name: "Western Michigan University",         domain: "wmubroncos.com" },
  { name: "Wichita State University",            domain: "goshockers.com" },
  { name: "William & Mary",                      domain: "tribeathletics.com" },
  { name: "Winthrop University",                 domain: "winthropeagles.com" },
  { name: "Wisconsin-Milwaukee",                 domain: "mkepanthers.com" },
  { name: "Wofford College",                     domain: "woffordterriers.com" },
  { name: "Wright State University",             domain: "wsuraiders.com" },
  { name: "University of Wyoming",               domain: "gowyo.com" },
  { name: "Xavier University",                   domain: "goxavier.com" },
  { name: "Yale University",                     domain: "yalebulldogs.com" },
  { name: "Youngstown State University",         domain: "ysupenguin.com" },
];

const RSS_PATHS = [
  { suffix: "sidearm",   path: "/rss.aspx" },
  { suffix: "sidearm2",  path: "/rss_feeds.aspx" },
  { suffix: "presto",    path: "/news/rss.xml" },
  { suffix: "rss",       path: "/rss" },
  { suffix: "feed",      path: "/feed" },
  { suffix: "newsfeed",  path: "/news/feed" },
];

const SCHOOL_SOURCES = SCHOOL_DOMAINS.flatMap(s =>
  RSS_PATHS.map(({ suffix, path }) => ({
    id: `school_${s.domain.replace(/\./g,'_')}_${suffix}`,
    name: s.name,
    url: `https://${s.domain}${path}`,
    school: s.name,
    domain: s.domain,
    type: "school"
  }))
);

module.exports = { TRADE_SOURCES, SCHOOL_SOURCES, SCHOOL_DOMAINS };
